### ISSUE TITLE
Setting configVars to no Suffix cause plugin to stop working.

### ISSUE THREAD

**Issue by gobigdale** [pixi-stix/sketch-mobile-assets#4]
This thing works great until I adjust configVars like this:

configVars = {

```
//Include a prefix? [yes/no]
includePrefix: "yes", 

// By default, it will prompt you to enter a prefix (examples: launcher, menu, stat_notify, tab, dialog). 
// Un-comment the next line to set a prefix manually instead: 
// prefixName: "prefix",


// Do you want to include a suffix? [yes/no]
includeSuffix: “no”,

// The default suffix is set to the page name (examples: normal, pressed, focused, disabled, selected). 
// Un-comment the next line to set a custom one manually instead:
//suffixName: "",


// This plugin works best if you design @1x, but if you design @2x (or 3x, or 4x) you can change this number here:
baseSize: 3,

// Include the asset width at the end of the file name? [yes/no]
size: "no"
```

After I do this plugin is available from menu, but will not do anything.

Thanks,
Dale

**Comment by gobigdale** [comment]
Any news on this? Was really hoping to make this plugin a major part of our workflow.

**Comment by pixi-stix** [comment]
Hey, thanks for reporting this. The issue is actually being caused by the quotes you used around "no"; they're typographic curly quotes (“ ”) instead of straight quotes (" "). If you edited this in a text editor like TextEdit, these quotes are probably being auto-replaced by the app. You can disable them by going to TextEdit > Preferences and unchecking "smart quotes", or do it through System Preferences > Keyboard > Text > unchecking "use smart quotes and dashes". (You also might want to make sure the final curly brace is at the end of the file- that would definitely cause issues.) Let me know if that fixes it!

**Comment by gobigdale** [comment]
Thank you for figuring this out!

From:  pixi-stix notifications@github.com
Reply-To:  pixi-stix/sketch-mobile-assets
<reply+002698821e384c2ff97c20fcb56ea475b7ffe5826533313592cf0000000110de18cb9
2a169ce0336e69a@reply.github.com>
Date:  Monday, January 26, 2015 at 7:01 AM
To:  pixi-stix/sketch-mobile-assets
sketch-mobile-assets@noreply.github.com
Cc:  Dale Jones gobigdale@gmail.com
Subject:  Re: [sketch-mobile-assets] Setting configVars to no Suffix cause
plugin to stop working. (#4)

Hey, thanks for reporting this. The issue is actually being caused by the
quotes you used around "no"; they're typographic curly quotes (³ ²) instead
of straight quotes (" "). If you edited this in a text editor like TextEdit,
these quotes are probably being auto-replaced by the app. You can disable
them by going to TextEdit > Preferences and unchecking "smart quotes", or do
it through System Preferences > Keyboard > Text > unchecking "use smart
quotes and dashes". (You also might want to make sure the final curly brace
is at the end of the file- that would definitely cause issues.) Let me know
if that fixes it!

‹
Reply to this email directly or view it on GitHub
<https://github.com/pixi-stix/sketch-mobile-assets/issues/4#issuecomment-714
73370> .
